[deps]
python = ">=3.10, <3.13"

[pip.deps]
numpy = ""
scipy = ""
pymatching = ""
ldpc = ">=2.2.8"
sinter = ">=1.14"
stim = ">=1.14"
fusion-blossom = ">=0.2.13"
quantum-pecos = ">=0.2.0"
panqec = ">=0.1.7"
mwpf = ">=0.2.6"
